In [1]:
import os
import yaml
from torch.utils.data import DataLoader
import argparse

from GeospatialFM.data import get_datasets
from GeospatialFM.models import *
# from utils import load_config
from torchgeo.samplers import RandomGeoSampler
from matplotlib import pyplot as plt

from transformers import TrainingArguments, Trainer
from transformers import AdamW, get_linear_schedule_with_warmup
from GeospatialFM.utils import setup, get_eval_fn, get_data, init_distributed_device
from GeospatialFM.data import *
from GeospatialFM.models import *
from GeospatialFM.loss import *

from sklearn.linear_model import LogisticRegression
from tqdm import tqdm
import numpy as np
from torch.utils.data import ConcatDataset
import segmentation_models_pytorch as smp

%load_ext autoreload
%autoreload 2

/home/haozhesi/anaconda3/envs/sat/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
device = torch.device('cuda:0')

In [3]:
args = {'exp_name': None,
        'config_file': 'GeospatialFM/configs/pretrain_cvit.yaml',
        'opts': None, 
        'save_config': False}
args = argparse.Namespace(**args)
args.debug = True
args.finetune = False
args

Namespace(exp_name=None, config_file='GeospatialFM/configs/pretrain_cvit.yaml', opts=None, save_config=False, debug=True, finetune=False)

In [24]:
device = init_distributed_device(args)
cfg, _ = setup(args)

AttributeError: 'Namespace' object has no attribute 'rank'

In [ ]:
cfg.DATASET['train_transforms']['normalize'] = True
cfg.DATASET['train_transforms']['standardize'] = False

In [ ]:
data = get_data(cfg)
data

In [ ]:
sample = iter(data['test'].dataloader).__next__()

In [8]:
sample['image'].shape

In [9]:
model = construct_mae(cfg.MODEL)

In [10]:
device = 'cuda:0'
device_ids = [0, 1, 2, 3]

In [11]:
model = model.to(device)
model = torch.nn.DataParallel(model, device_ids=device_ids)

In [12]:
loss = get_loss_list(cfg.LOSS)

In [13]:
loss

In [ ]:
device = torch.device(device)

In [ ]:
# image = sample['image'].to(device, non_blocking=True)
# radar = sample['radar'].to(device, non_blocking=True)
image = sample['image']
radar = sample['radar']

In [ ]:
# model_out = model(image, radar)
# logit_scale = model_out.get("logit_scale").mean()
# model_out['logit_scale'] = logit_scale

In [ ]:
# points = [[20, 193], [35, 180], [55, 150], [130, 180], [95, 140], [30, 25], [80, 30]]
points = [[45, 10], [45, 20]]
cross_length = 5
img_id = 100
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
color = ['r', 'g', 'b', 'cyan', 'orange', 'purple', 'brown']
for c, point in enumerate(points):
    curve = image[img_id, :, point[0], point[1]].detach().cpu().numpy()
    curve = np.delete(curve, 10)
    plt.plot(np.arange(12), curve, color[c])
vis_img = image[img_id, [3, 2, 1], :, :].detach().cpu().numpy().transpose(1, 2, 0)
# normalize each channel
vis_img = (vis_img - vis_img.min()) / (vis_img.max() - vis_img.min())

plt.subplot(1, 2, 2)
plt.imshow(vis_img)
# draw a cross at the point
for c, point in enumerate(points):
    plt.plot([point[1] - cross_length, point[1] + cross_length], [point[0], point[0]],  color[c]) 
    # Draw vertical line of the cross
    plt.plot([point[1], point[1]], [point[0] - cross_length, point[0] + cross_length],  color[c]) 
# plt.axis('off')

In [ ]:
# points = [[20, 193], [35, 180], [55, 150], [130, 180], [95, 140], [30, 25], [80, 30]]
points = [[45, 10], [45, 20]]
cross_length = 5
img_id = 150
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
color = ['r', 'g', 'b', 'cyan', 'orange', 'purple', 'brown']
for c, point in enumerate(points):
    curve = radar[img_id, :, point[0], point[1]].detach().cpu().numpy()
    # curve = np.delete(curve, 10)
    plt.plot(np.arange(2), curve, color[c])
vis_img = radar[img_id, [0], :, :].detach().cpu().numpy().transpose(1, 2, 0)
# normalize each channel
vis_img = (vis_img - vis_img.min()) / (vis_img.max() - vis_img.min())

plt.subplot(1, 2, 2)
plt.imshow(vis_img)
# draw a cross at the point
for c, point in enumerate(points):
    plt.plot([point[1] - cross_length, point[1] + cross_length], [point[0], point[0]],  color[c]) 
    # Draw vertical line of the cross
    plt.plot([point[1], point[1]], [point[0] - cross_length, point[0] + cross_length],  color[c]) 
# plt.axis('off')

In [1]:
from GeospatialFM.models.costum_layers import *
import torch

%load_ext autoreload
%autoreload 2

/home/haozhesi/anaconda3/envs/sat/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
sample = torch.randn(2, 13, 224, 224)

In [53]:
patch_embedding = PatchEmbedPerChannel(in_chans=13)

In [54]:
extra_tokens = dict()
extra_tokens["channels"] = torch.tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
out = patch_embedding(sample, extra_tokens)

In [57]:
collpase_channels(out[0], 'mean').shape

torch.Size([2, 768])

In [61]:
out[1].shape

torch.Size([2, 13])

In [ ]:
out[1]

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [35]:
13*0.25

3.25

In [21]:
x = sample
B, Cin, H, W = x.shape
# Note: The current number of channels (Cin) can be smaller or equal to in_chans
len_keep = int(Cin * 0.4)

noise = torch.rand(B, Cin, device=x.device)  # noise in [0, 1]
# sort noise for each sample
ids_shuffle = torch.argsort(noise, dim=1)  # ascend: small is keep, large is remove
ids_restore = torch.argsort(ids_shuffle, dim=1)

# keep the first subset
ids_keep = ids_shuffle[:, :len_keep]

In [68]:
ids_keep.unsqueeze(-1).unsqueeze(-1).repeat(1, 5, 224, 224)

tensor([[[[ 5,  5,  5,  ...,  5,  5,  5],
          [ 5,  5,  5,  ...,  5,  5,  5],
          [ 5,  5,  5,  ...,  5,  5,  5],
          ...,
          [ 5,  5,  5,  ...,  5,  5,  5],
          [ 5,  5,  5,  ...,  5,  5,  5],
          [ 5,  5,  5,  ...,  5,  5,  5]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 6,  6,  6,  ...,  6,  6,  6],
          [ 6,  6,  6,  ...,  6,  6,  6],
          [ 6,  6,  6,  ...,  6,  6,  6],
          ...,
          [ 6,  6,  6,  ...,  6,  6,  6],
          [ 6,  6,  6,  ...,  6,  6,  6],
          [ 6,  6,  6,  ...,  6,  6,  6]],

         ...,

         [[ 6,  6,  6,  ...,  6,  6,  6],
          [ 6,  6,  6,  ...,  6,  6,  6],
          [ 6,  6,  6,  ...,  6,  6,  6],
          ...,
          [ 6,  6,  6,  ...,  6,  6, 

In [52]:
ids_keep.shape
# sample corresponding channels from ce
new_ce = torch.gather(ce, 2, ids_keep.unsqueeze(1).repeat(1, ce.shape[1], 1))

In [50]:
new_ce[0, :5, 0], ids_keep[0, 0], ce[0, :5, 2]

(tensor([ 0.0149,  0.0129,  0.0069, -0.0358,  0.0500],
        grad_fn=<SelectBackward0>),
 tensor(2),
 tensor([ 0.0149,  0.0129,  0.0069, -0.0358,  0.0500],
        grad_fn=<SelectBackward0>))

In [46]:
new_ce[0, :5].shape

torch.Size([5, 5])

In [49]:
ce[0, :5, 2].shape

torch.Size([5])

In [77]:
# gather the C dim of the batch of the images in shape B x C x H x W following the index of ids_keep
x_keep = torch.gather(x, dim=1, index=ids_keep.unsqueeze(-1).unsqueeze(-1).repeat(1, 1, *x.shape[-2:]))

In [78]:
x_keep.shape

torch.Size([2, 5, 224, 224])

In [79]:
# generate the binary mask: 0 is keep, 1 is remove
mask = torch.ones([B, Cin], device=x.device)
mask[:, :len_keep] = 0
# unshuffle to get the binary mask
mask = torch.gather(mask, dim=1, index=ids_restore)
# Per batch channel sampling
        # Note this may be slow

In [80]:
mask

tensor([[0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0.],
        [1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0.]])

In [81]:
ids_keep

tensor([[ 5,  1,  6, 12,  0],
        [ 2, 11,  1, 12,  8]])

In [2]:
embedding = torch.rand((2, 3, 10))

In [4]:
embedding.shape

torch.Size([2, 3, 10])

In [2]:
in_chans = 13
embed_dim = 768
patch_size = 16
sample = torch.randn(320, 13, 224, 224)
proj = nn.Conv2d(
    in_chans,
    embed_dim*in_chans,
    kernel_size=(patch_size, patch_size),
    stride=(patch_size, patch_size),
    groups=in_chans,
)  # CHANGED

In [8]:
proj2 = nn.Conv2d(
    in_chans,
    embed_dim,
    kernel_size=(patch_size, patch_size),
    stride=(patch_size, patch_size),
    bias=False
)  # CHANGED

In [9]:
proj3 = nn.Conv3d(
    1,
    embed_dim*in_chans,
    kernel_size=(1, patch_size, patch_size),
    stride=(1, patch_size, patch_size),
    bias=False
)  # CHANGED

In [5]:
[p for p in proj.parameters()]

[Parameter containing:
 tensor([[[[ 0.0249,  0.0120, -0.0572,  ..., -0.0511,  0.0248, -0.0440],
           [-0.0441, -0.0587, -0.0619,  ..., -0.0135, -0.0402, -0.0045],
           [ 0.0261, -0.0029, -0.0119,  ..., -0.0543, -0.0530,  0.0458],
           ...,
           [ 0.0007, -0.0545, -0.0185,  ..., -0.0523, -0.0208,  0.0074],
           [-0.0507, -0.0495,  0.0356,  ..., -0.0488, -0.0101, -0.0257],
           [ 0.0596, -0.0471, -0.0401,  ...,  0.0415,  0.0226,  0.0603]]],
 
 
         [[[ 0.0493, -0.0200, -0.0521,  ...,  0.0328, -0.0307,  0.0097],
           [-0.0096, -0.0445,  0.0035,  ..., -0.0113, -0.0321, -0.0437],
           [-0.0133, -0.0105,  0.0075,  ...,  0.0067, -0.0246, -0.0270],
           ...,
           [-0.0479, -0.0200, -0.0334,  ...,  0.0114,  0.0499,  0.0596],
           [ 0.0273,  0.0388, -0.0519,  ...,  0.0378,  0.0034,  0.0187],
           [-0.0167, -0.0244,  0.0042,  ...,  0.0125,  0.0044,  0.0012]]],
 
 
         [[[ 0.0190, -0.0377, -0.0300,  ...,  0.0076,  0.

In [6]:
[p.numel() for p in proj2.parameters()]

[2555904, 768]

In [10]:
# print the number of parameters
w1 = sum(p.numel() for p in proj.parameters())
w2 = sum(p.numel() for p in proj2.parameters())
w3 = sum(p.numel() for p in proj3.parameters())
w1-w2, w3-w2

(9984, 0)

In [24]:
w1 = proj.weight.flatten().shape[0]
w2 = proj2.weight.flatten().shape[0]
w3 = proj3.weight.flatten().shape[0]
w1-w2, w3-w2

(0, -2359296)

In [25]:
b1 = proj.bias.flatten().shape[0]
b2 = proj2.bias.flatten().shape[0]
b3 = proj3.bias.flatten().shape[0]
w1-w2, w3-w2

(0, -2359296)

In [26]:
proj.to('cuda:1')
proj2.to('cuda:1')
proj3.to('cuda:1')
sample = sample.to('cuda:1')

In [27]:
# estimate the timw of the forward pass
import time
start = time.time()
out1 = proj(sample).cpu()
end = time.time()
print(end - start)

start = time.time()
out2 = proj2(sample).cpu()
end = time.time()
print(end - start)

start = time.time()     
out3 = proj3(sample.unsqueeze(1)).cpu()
end = time.time()
print(end - start)

2.902925729751587
0.1449604034423828
1.4818251132965088


In [8]:
sample[:, torch.tensor([0, 1, 11])].shape

torch.Size([320, 3, 224, 224])

In [9]:
out1.shape

torch.Size([320, 9984, 14, 14])

In [10]:
out3.shape

torch.Size([320, 768, 13, 14, 14])

In [1]:
import random

0.40318025746819064

In [6]:
random.uniform(0.25, 0.75)

0.5470134688105862

In [1]:
import torch
import torch.nn as nn

In [2]:
sample = torch.randn(2, 1, 224, 224)

In [9]:
proj = nn.Conv3d(
    1,
    1024,
    kernel_size=(1, 4, 4),
    stride=(1, 4, 4),
)

In [10]:
proj2 = nn.Conv3d(
    1024,
    768, 
    kernel_size=(1, 4, 4),
    stride=(1, 4, 4),
)

In [11]:
proj3 = nn.Conv3d(
    768,
    768, 
    kernel_size=(1, 1, 1),
    stride=(1, 1, 1),
)

In [12]:
proj3(proj2(proj(sample.unsqueeze(1)))).shape

torch.Size([2, 768, 1, 14, 14])

In [4]:
embed_dim = 768
proj = nn.Conv3d(
        embed_dim*2,
        embed_dim,
        kernel_size=(1, 1, 1),
        stride=(1, 1, 1),
    )
w = sum(p.numel() for p in proj.parameters())
w

1180416

In [3]:
2*embed_dim**2

1179648

In [8]:
import os
import pickle

In [9]:
cache_path = 'results/cache/BigEarthNet_vit_base_patch16_224_mae_base_finetune_OPTICAL/'

In [15]:
def load_features(cache_path, split):
    # list all files in cache_path containing split
    cache_files = [f for f in os.listdir(cache_path) if split in f and f.endswith('.pkl')]
    cache_files.sort()
    features = dict(label=[], img_feature=[])
    for f_name in cache_files:
        print(f_name)
        with open(os.path.join(cache_path, f_name), 'rb') as f:
            chunk_features = pickle.load(f)
            print(chunk_features)
            features['label'].append(chunk_features['label'])
            features['img_feature'].append(chunk_features['img_feature'])
    print(features['label'])
    features['label'] = torch.cat(features['label'], dim=0)
    features['img_feature'] = torch.cat(features['img_feature'], dim=0)
    return features

In [16]:
load_features(cache_path, 'test')

test_0.pkl
{'label': tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]), 'img_feature': tensor([[-3.1885e-01,  1.6117e+00,  2.1697e-01,  ...,  3.7698e-02,
         -4.4898e-01, -1.7372e-01],
        [-7.7706e-01,  1.5149e+00,  2.2011e-01,  ...,  6.7384e-02,
         -7.6155e-01, -3.2737e-01],
        [-5.1657e-01,  1.5541e+00,  1.7843e-01,  ...,  4.7636e-04,
         -5.6955e-01, -1.8474e-01],
        ...,
        [ 1.1849e+00,  7.6028e-02,  2.8320e-01,  ..., -1.3394e+00,
          4.9319e-01, -5.1993e-01],
        [ 9.4090e-01,  7.7789e-02, -1.1849e-01,  ..., -1.3606e+00,
          1.1600e+00,  7.6003e-02],
        [ 9.3445e-01,  1.0632e-01,  2.5254e-01,  ..., -1.5855e+00,
          4.0105e-01, -3.8780e-02]])}
test_1.pkl
{'label': tensor([[0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0.

TypeError: string indices must be integers

In [1]:
import torch
import torch.nn as nn

In [21]:
class ChannelINN(nn.Module):
    def __init__(self, n_nodes, out_channels, kernel_size, stride, padding=0):
        super(ChannelINN, self).__init__()
        self.conv = nn.Conv3d(1, n_nodes*out_channels, kernel_size, stride, padding)
        self.n_nodes = n_nodes
        self.out_channels = out_channels
        self._x = torch.linspace(0, 1, n_nodes)
    
    # def _interpolate(self, x, idx):
    def _intergral(self, x, idx):
        pass
        # x in shape B x n_nodes x C_out x H x W
        
 
    def forward(self, x, x_idx):
        # x in shape B x 1 x C x H x W
        assert x_idx.shape[0] == x.shape[2]
        x = self.conv(x) # B x n_nodes*out_channels C x H x W
        B, _, C, H, W = x.shape
        x = x.view(B, self.n_nodes, self.out_channels, C, H, W)
        x_ = torch.zeros(B, self.out_channels, C, H, W, device=x.device)
        for i in range(C):
            idx = x_idx[i]
            fx = x[:, :, :, i, :, :]
            x_[:, :, i, :, :] = self._interpolate(fx, idx)

        return x

In [22]:
model = ChannelINN(20, 768, (1, 16, 16), (1, 16, 16))
sample = torch.randn(2, 13, 224, 224)

In [23]:
model(sample.unsqueeze(1), torch.arange(13)).shape

torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])
torch.Size([2, 20, 768, 14, 14])


torch.Size([2, 20, 768, 13, 14, 14])