- eval:
    - test-time and train-time feed-forward
    - channel mask and recon
    - patch_embedding

In [1]:
from GeospatialFM.models.channel_vit import ChannelViTEncoder
from GeospatialFM.models.vision_transformer import ViTEncoder, ViTDecoder
import torch
from GeospatialFM.models.mae import CrossModalMAEViT
from GeospatialFM.loss.mae_loss import SpectralInterpolationLoss

%load_ext autoreload
%autoreload 2

/home/haozhesi/anaconda3/envs/sat/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]


In [2]:
optical_sample = torch.randn(2, 13, 224, 224)
radar_sample = torch.randn(2, 2, 224, 224)

In [4]:
optical_encoder = ChannelViTEncoder(in_chans=13, channel_pool='max')
decoder = ViTDecoder(out_chans=1)
radar_encoder = ViTEncoder(in_chans=2)

In [13]:
output = optical_encoder.forward_encoder(optical_sample, 0.75, 0.75)

In [14]:
output[0].shape

torch.Size([2, 50, 768])

In [15]:
decoder.forward_decoder(output[0], output[2])

torch.Size([2, 197, 512]) torch.Size([1, 197, 512])


tensor([[[-0.7051, -0.4137,  0.5056,  ...,  1.1126, -0.2831,  1.2745],
         [-0.2731, -0.9788,  0.7971,  ...,  1.7451, -0.1485,  2.8475],
         [-0.2973, -0.8184,  0.1562,  ...,  1.2689, -0.6946,  2.8652],
         ...,
         [-0.3789, -0.7623,  0.2767,  ...,  1.0466, -0.7341,  1.9349],
         [-0.3095, -0.5366, -0.0150,  ...,  1.4688,  0.1190,  1.3902],
         [-0.4230, -0.4572, -0.0452,  ...,  1.4058,  0.1243,  1.4625]],

        [[-0.6358, -0.5975,  0.3561,  ...,  1.1643, -0.1703,  1.2867],
         [-0.4686, -0.4378,  0.1883,  ...,  1.2375, -0.0083,  1.5312],
         [-0.3208, -0.2296,  0.1140,  ...,  1.3060,  0.2299,  1.6545],
         ...,
         [-0.2225, -0.7245, -0.0314,  ...,  1.5588,  0.1938,  1.2986],
         [-0.2470, -0.7679, -0.0999,  ...,  1.5500,  0.2303,  1.3721],
         [-0.6867, -0.8678, -0.2532,  ...,  0.8614, -0.7432,  1.6795]]],
       grad_fn=<SliceBackward0>)

In [11]:
optical_encoder.num_patches / 13

196.0

In [22]:
mae = CrossModalMAEViT(optical_encoder, radar_encoder, decoder, decoder).train()

In [23]:
out = mae(optical_sample, radar_sample, 0.75, 11/12)

torch.Size([2, 196, 768]) torch.Size([2, 13])
torch.Size([2, 196, 768]) torch.Size([2, 3328])


In [29]:
out['optical_target'].shape[-1]

3328

In [7]:
optical_sample[:, 1]

tensor([[[-0.0758,  0.2432, -0.6127,  ..., -0.1294,  1.4540,  0.4133],
         [-0.0375,  0.4410,  0.3831,  ...,  0.9347,  0.1333,  0.5123],
         [ 1.0506,  0.4840, -1.4962,  ...,  0.4558, -1.2226, -1.9523],
         ...,
         [-0.8677,  0.2095,  1.0767,  ...,  0.1305, -0.4224, -1.1259],
         [ 0.1310,  0.6436,  0.3972,  ...,  0.8091,  0.2456, -0.2861],
         [-0.3486, -0.0320, -0.4587,  ...,  1.3762,  1.0520,  0.9561]],

        [[ 0.4941, -0.6912, -0.8781,  ...,  0.3940, -0.5473,  1.5865],
         [ 0.8113,  0.3332,  1.1681,  ...,  1.6995,  1.7562, -0.0785],
         [-0.5545, -0.0641, -0.0493,  ..., -1.2583,  1.1410, -0.8450],
         ...,
         [ 1.2646, -0.3340, -0.5218,  ...,  1.1230, -0.4622, -0.0545],
         [ 0.5374, -0.1509, -1.1492,  ..., -0.3861, -1.7037,  0.2794],
         [-1.3677,  0.2773,  1.6956,  ...,  0.3460,  1.3639,  0.2401]]])

In [9]:
out['optical_channel_mask'].shape

torch.Size([2, 3328])

In [39]:
out['optical_channel_mask'][1].reshape(256, 13)[0]

tensor([1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [171]:
loss = SpectralInterpolationLoss()
loss(**out, output_dict=True)

{'optical_channel_mse': tensor(0.8883, grad_fn=<MulBackward0>),
 'radar_channel_mse': tensor(0.8874, grad_fn=<MulBackward0>)}

In [160]:
for key in out.keys():
    print(key, out[key].shape)

optical_mask torch.Size([2, 196])
radar_mask torch.Size([2, 196])
optical_recon torch.Size([2, 196, 3840])
radar_recon torch.Size([2, 196, 3840])
optical_target torch.Size([2, 196, 3328])
radar_target torch.Size([2, 196, 512])
optical_cls_token torch.Size([2, 768])
radar_cls_token torch.Size([2, 768])
logit_scale torch.Size([])
optical_channel_mask torch.Size([2, 3328])


In [86]:
3840 / 15

256.0

In [112]:
optical_target = out['optical_target']
optical_recon = out['optical_recon']
radar_recon = out['radar_recon']
B, L, D = optical_target.shape

In [165]:
def _forward_channel_mse_one_modal(recon, target, mask):
    B, L, D = target.shape
    recon = recon[:, :, :D]
    loss = (recon - target).abs()
    loss = loss.mean(dim=1)
    if mask.sum() == 0:
        return loss.mean() # if no mask, mean loss on all channels
    loss = (loss * mask).sum() / mask.sum()  # mean loss on removed patches
    return loss

In [162]:
optical_recon.shape, optical_target.shape

(torch.Size([2, 196, 3840]), torch.Size([2, 196, 3328]))

In [163]:
mask = out['optical_channel_mask']

In [166]:
_unimodal_channel_loss(optical_recon, optical_target, mask)

torch.Size([2, 3328]) tensor(0.8925, grad_fn=<DivBackward0>)


In [ ]:
optical_loss = optical_recon[:, :, :D]
radar_recon_o = radar_recon[:, :, :D]

In [ ]:
expanded_mask = mask.unsqueeze(1).unsqueeze(1).expand(B, L, 256, -1).reshape(B, L, D)


In [ ]:
recon_channels = (expanded_mask * radar_recon_o)
recon_channels.shape

torch.Size([2, 196, 3328])